### ISSUE TITLE
standarden cpu socket

### ISSUE THREAD

**Issue by IzidorM** [iksordoo/OVUM---Efekt-9V#13]
Razmisliti je potrebno se o bolj standardnem pinoutu za cpu. Po
moznosti tak, za katerega obstajajo 48 in 64 pinske verzije istega
cpu-ja... Pinout naj bo tak, da bo cim lazje programirati cpu-je v
primeru prodaje le-teh samih s prednalozenim fw.

**Comment by iksordoo** [comment]
Je ...
